### ISSUE TITLE
Error: Cannot find module "."

### ISSUE THREAD

**Issue by ypkkhatri** [simonepri/project-version#4]
![image](https://user-images.githubusercontent.com/16644003/38362265-745f5d54-38d0-11e8-92cc-1ebbdda45cb2.png)

**Comment by ypkkhatri** [comment]
I have done just below code

```
import version from 'project-version'
console.log(version);
```

**Comment by simonepri** [comment]
Thank you for the issue!
Are you using it with webpack, right?

Can you create a small repo to let me able to reproduce the error? 
This would speedup the bug fix.

**Comment by ypkkhatri** [comment]
I'm using in my angular 5 project
